import 'package:adhan/adhan.dart';
import 'package:geolocator/geolocator.dart';

import '../models/app_settings.dart';
import '../models/schedule.dart';

class PrayerTimeResult {
  final String name;
  final DateTime time;
  PrayerTimeResult(this.name, this.time);
}

class PrayerTimeService {
  static Future<Position> getCurrentLocation() async {
    LocationPermission permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
    }
    if (permission == LocationPermission.denied ||
        permission == LocationPermission.deniedForever) {
      throw Exception('Location permission denied');
    }
    return Geolocator.getCurrentPosition();
  }

  static CalculationParameters _paramsFor(CalculationMethodOption option) {
    switch (option) {
      case CalculationMethodOption.muslimWorldLeague:
        return CalculationMethod.muslim_world_league.getParameters();
      case CalculationMethodOption.egyptian:
        return CalculationMethod.egyptian.getParameters();
      case CalculationMethodOption.karachi:
        return CalculationMethod.karachi.getParameters();
      case CalculationMethodOption.ummAlQura:
        return CalculationMethod.umm_al_qura.getParameters();
      case CalculationMethodOption.dubai:
        return CalculationMethod.dubai.getParameters();
      case CalculationMethodOption.moonsightingCommittee:
        return CalculationMethod.moon_sighting_committee.getParameters();
      case CalculationMethodOption.northAmerica:
        return CalculationMethod.north_america.getParameters();
      case CalculationMethodOption.kuwait:
        return CalculationMethod.kuwait.getParameters();
      case CalculationMethodOption.qatar:
        return CalculationMethod.qatar.getParameters();
      case CalculationMethodOption.singapore:
        return CalculationMethod.singapore.getParameters();
    }
  }

  static List<PrayerTimeResult> calculateToday({
    required double latitude,
    required double longitude,
    required CalculationMethodOption method,
    DateTime? date,
  }) {
    final coordinates = Coordinates(latitude, longitude);
    final params = _paramsFor(method);
    final dateComponents = DateComponents.from(date ?? DateTime.now());
    final prayerTimes = PrayerTimes(coordinates, dateComponents, params);

    return [
      PrayerTimeResult('Fajr', prayerTimes.fajr),
      PrayerTimeResult('Dhuhr', prayerTimes.dhuhr),
      PrayerTimeResult('Asr', prayerTimes.asr),
      PrayerTimeResult('Maghrib', prayerTimes.maghrib),
      PrayerTimeResult('Isha', prayerTimes.isha),
    ];
  }

  /// Generates auto-schedules from calculated prayer times, applying the
  /// configured prayer duration as the silence window length. These
  /// carry `isAutoGenerated = true` so they can be safely refreshed
  /// daily without touching user-made schedules.
  static List<Schedule> buildAutoSchedules({
    required double latitude,
    required double longitude,
    required AppSettings settings,
  }) {
    final times = calculateToday(
      latitude: latitude,
      longitude: longitude,
      method: settings.calculationMethod,
    );

    return times.map((p) {
      final startMinutes = p.time.hour * 60 + p.time.minute;
      final endMinutes = startMinutes + settings.prayerDurationMinutes;
      return Schedule(
        id: 'auto_${p.name.toLowerCase()}',
        name: p.name,
        startMinutes: startMinutes,
        endMinutes: endMinutes,
        activeDays: const [1, 2, 3, 4, 5, 6, 7],
        enabled: true,
        mode: settings.defaultMode,
        restoreBehavior: settings.restoreBehavior,
        isAutoGenerated: true,
      );
    }).toList();
  }
}
