import 'package:hive/hive.dart';

part 'schedule.g.dart';

/// Mode the phone should be switched to when a schedule becomes active.
@HiveType(typeId: 1)
enum SilenceMode {
  @HiveField(0)
  vibrate,
  @HiveField(1)
  silent,
  @HiveField(2)
  dnd,
}

/// What to restore to once the schedule period ends.
@HiveType(typeId: 2)
enum RestoreBehavior {
  @HiveField(0)
  previousMode,
  @HiveField(1)
  alwaysNormal,
}

/// A single silence schedule (e.g. "Fajr", "Dhuhr", or a custom one).
@HiveType(typeId: 0)
class Schedule extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String name;

  /// Minutes since midnight, e.g. 5:00 AM = 300
  @HiveField(2)
  int startMinutes;

  @HiveField(3)
  int endMinutes;

  /// 1 = Monday ... 7 = Sunday (ISO-8601), matches DateTime.weekday
  @HiveField(4)
  List<int> activeDays;

  @HiveField(5)
  bool enabled;

  @HiveField(6)
  SilenceMode mode;

  @HiveField(7)
  RestoreBehavior restoreBehavior;

  /// true if this schedule was generated automatically from calculated
  /// prayer times (Prayer Time Mode) rather than added manually.
  @HiveField(8)
  bool isAutoGenerated;

  /// Stores the ringer mode that was active right before this schedule
  /// fired, so we know what to restore to. Null until the schedule fires.
  @HiveField(9)
  int? savedRingerMode;

  Schedule({
    required this.id,
    required this.name,
    required this.startMinutes,
    required this.endMinutes,
    required this.activeDays,
    this.enabled = true,
    this.mode = SilenceMode.vibrate,
    this.restoreBehavior = RestoreBehavior.previousMode,
    this.isAutoGenerated = false,
    this.savedRingerMode,
  });

  Duration get startOfDay => Duration(minutes: startMinutes);
  Duration get endOfDay => Duration(minutes: endMinutes);

  String get startLabel => _fmt(startMinutes);
  String get endLabel => _fmt(endMinutes);

  static String _fmt(int minutes) {
    final h24 = (minutes ~/ 60) % 24;
    final m = minutes % 60;
    final h12 = h24 % 12 == 0 ? 12 : h24 % 12;
    final period = h24 < 12 ? 'AM' : 'PM';
    return '${h12.toString().padLeft(2, '0')}:${m.toString().padLeft(2, '0')} $period';
  }

  Schedule copyWith({
    String? id,
    String? name,
    int? startMinutes,
    int? endMinutes,
    List<int>? activeDays,
    bool? enabled,
    SilenceMode? mode,
    RestoreBehavior? restoreBehavior,
    bool? isAutoGenerated,
    int? savedRingerMode,
  }) {
    return Schedule(
      id: id ?? this.id,
      name: name ?? this.name,
      startMinutes: startMinutes ?? this.startMinutes,
      endMinutes: endMinutes ?? this.endMinutes,
      activeDays: activeDays ?? List.from(this.activeDays),
      enabled: enabled ?? this.enabled,
      mode: mode ?? this.mode,
      restoreBehavior: restoreBehavior ?? this.restoreBehavior,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      savedRingerMode: savedRingerMode ?? this.savedRingerMode,
    );
  }
}
